export const MAIN_SYMPTOMS: string[] = [
  'Dor no peito',
  'Falta de ar',
  'Dor de cabeça',
  'Febre',
  'Tosse',
  'Dor abdominal',
  'Náusea / Vômito',
  'Diarreia',
  'Dor nas costas',
  'Tontura / Vertigem',
  'Desmaio / Perda de consciência',
  'Dor de garganta',
  'Fraqueza / Cansaço extremo',
  'Formigamento / Dormência',
  'Dor nos membros',
  'Alteração visual súbita',
  'Confusão mental',
  'Dificuldade para falar',
  'Dor no ouvido',
  'Sangramento',
];

export const ASSOCIATED_SYMPTOMS: string[] = [
  'Sudorese fria',
  'Palpitações / Coração acelerado',
  'Inchaço (edema)',
  'Dificuldade para engolir',
  'Perda de apetite',
  'Amarelamento da pele (icterícia)',
  'Manchas na pele',
  'Dor ao urinar',
  'Urina escura',
  'Fezes com sangue',
  'Rigidez no pescoço',
  'Sensibilidade à luz',
  'Vômito com sangue',
  'Desmaio após esforço',
  'Inchaço no rosto / lábios',
];
